// 직접 작성 시 예상 소요 시간 (분)
export const MANUAL_WRITE_MINUTES = {
  회의안건: 20,
  회의록: 40,
  주간보고: 30,
};

export const DOCUMENT_TYPES = [
  {
    id: '주간현황판',
    label: '주간 현황판',
    icon: '🗓️',
    description: 'Monday 이번 주 마감 현황',
    color: 'red',
    fields: [],
    special: 'weekly',
  },
  {
    id: '회의록',
    label: '회의록',
    icon: '📝',
    description: '회의 결과 및 결정사항 기록',
    color: 'teal',
    fields: [
      { id: 'title', label: '회의 제목', type: 'text', placeholder: '예) 2026년 1분기 마케팅 전략 회의', required: true },
      { id: 'datetime', label: '회의 일시', type: 'text', placeholder: '예) 2026년 3월 20일 (목) 오후 2시', required: true },
      { id: 'location', label: '회의 장소', type: 'text', placeholder: '예) 본사 3층 대회의실 / Zoom 온라인', required: true },
      { id: 'attendees', label: '참석자', type: 'text', placeholder: '예) 마케팅팀 김철수, 이영희 / 영업팀 박민준', required: true },
      { id: 'purpose', label: '회의 목적', type: 'textarea', placeholder: '이 회의의 목적을 입력하세요.', required: true },
      { id: 'discussions', label: '논의 내용', type: 'textarea', placeholder: '예)\n1. 1분기 실적 리뷰 - 목표 대비 85% 달성, 주요 원인 분석\n2. 2분기 캠페인 계획 - SNS 광고 예산 증액 논의\n3. 예산 배분 - 디지털 마케팅 비중 확대 결정', required: true },
      { id: 'decisions', label: '결정사항', type: 'textarea', placeholder: '회의에서 최종 결정된 사항을 입력하세요.', required: true },
      { id: 'actions', label: '후속 조치 사항', type: 'textarea', placeholder: '예)\n- 김철수: SNS 광고 제안서 작성 (3/27까지)\n- 이영희: 예산안 재검토 및 보고 (3/25까지)', required: true },
      { id: 'nextMeeting', label: '다음 회의 일정', type: 'text', placeholder: '예) 2026년 4월 3일 오후 2시 (미정)', required: false },
    ],
  },
  {
    id: '주간보고',
    label: '주간 보고',
    icon: '📊',
    description: '주간 업무 현황 및 계획 보고',
    color: 'purple',
    fields: [
      { id: 'period', label: '보고 기간', type: 'text', placeholder: '예) 2026년 3월 30일 ~ 4월 3일', required: true },
      { id: 'completed', label: '이번 주 완료 업무', type: 'textarea', placeholder: '예)\n- 신규 기능 A 개발 완료\n- 코드 리뷰 3건 처리', required: false },
      { id: 'inProgress', label: '진행 중인 업무', type: 'textarea', placeholder: '예)\n- 기능 B 개발 (80% 완료)\n- 버그 수정 2건', required: true },
      { id: 'nextPlan', label: '다음 주 계획', type: 'textarea', placeholder: '예)\n- 기능 B 개발 완료 및 테스트\n- 배포 준비', required: false },
      { id: 'issues', label: '이슈 및 리스크', type: 'textarea', placeholder: '현재 발생한 이슈나 예상되는 리스크를 입력하세요.', required: false },
    ],
  },
  {
    id: '회의안건',
    label: '회의 안건',
    icon: '📌',
    description: '회의 준비 및 안건 정리',
    color: 'green',
    fields: [
      { id: 'title', label: '회의 제목', type: 'text', placeholder: '예) 2026년 1분기 스프린트 회고 및 2분기 로드맵 회의', required: true },
      { id: 'datetime', label: '회의 일시', type: 'text', placeholder: '예) 2026년 3월 20일 (금) 오후 2시', required: true },
      { id: 'location', label: '회의 장소', type: 'text', placeholder: '예) 개발실 회의실 A / Google Meet', required: true },
      { id: 'attendees', label: '참석자', type: 'text', placeholder: '예) 개발팀 전원, 기획팀 PM, QA 팀장', required: true },
      { id: 'purpose', label: '회의 목적', type: 'textarea', placeholder: '예) 1분기 스프린트 결과를 회고하고 미해결 기술 부채를 정리한 뒤, 2분기 개발 로드맵 우선순위를 팀 전체가 합의한다.', required: true },
      { id: 'topics', label: '논의 안건', type: 'textarea', placeholder: '예)\n1. 1분기 스프린트 회고 (완료 항목 / 미완료 항목 / 블로커 원인 분석)\n2. 기술 부채 목록 검토 및 우선순위 결정\n3. 2분기 주요 기능 개발 일정 및 담당자 배정\n4. CI/CD 파이프라인 개선 방향 논의\n5. 기타 (코드 리뷰 프로세스 개선 제안)', required: true },
      { id: 'preparation', label: '사전 준비 사항', type: 'textarea', placeholder: '예)\n- 각 개발자: 담당 스프린트 항목 완료율 및 이슈 정리 (회의 전날까지)\n- PM: 2분기 요구사항 목록 및 우선순위 초안 공유\n- 팀장: 기술 부채 목록 최신화', required: false },
    ],
  },
];

export const COLOR_CLASSES = {
  teal: {
    bg: 'bg-teal-50',
    border: 'border-teal-200',
    selectedBorder: 'border-teal-500',
    selectedBg: 'bg-teal-50',
    icon: 'bg-teal-100',
    badge: 'bg-teal-100 text-teal-700',
    button: 'bg-teal-600 hover:bg-teal-700',
    ring: 'ring-teal-500',
    text: 'text-teal-700',
  },
  blue: {
    bg: 'bg-blue-50',
    border: 'border-blue-200',
    selectedBorder: 'border-blue-500',
    selectedBg: 'bg-blue-50',
    icon: 'bg-blue-100',
    badge: 'bg-blue-100 text-blue-700',
    button: 'bg-blue-600 hover:bg-blue-700',
    ring: 'ring-blue-500',
    text: 'text-blue-700',
  },
  green: {
    bg: 'bg-green-50',
    border: 'border-green-200',
    selectedBorder: 'border-green-500',
    selectedBg: 'bg-green-50',
    icon: 'bg-green-100',
    badge: 'bg-green-100 text-green-700',
    button: 'bg-green-600 hover:bg-green-700',
    ring: 'ring-green-500',
    text: 'text-green-700',
  },
  purple: {
    bg: 'bg-purple-50',
    border: 'border-purple-200',
    selectedBorder: 'border-purple-500',
    selectedBg: 'bg-purple-50',
    icon: 'bg-purple-100',
    badge: 'bg-purple-100 text-purple-700',
    button: 'bg-purple-600 hover:bg-purple-700',
    ring: 'ring-purple-500',
    text: 'text-purple-700',
  },
  red: {
    bg: 'bg-red-50',
    border: 'border-red-200',
    selectedBorder: 'border-red-500',
    selectedBg: 'bg-red-50',
    icon: 'bg-red-100',
    badge: 'bg-red-100 text-red-700',
    button: 'bg-red-600 hover:bg-red-700',
    ring: 'ring-red-500',
    text: 'text-red-700',
  },
};
